import { NextResponse } from "next/server";

const headers = [
  "Oops! Lost in Space",
  "Page Not Found",
  "Whoopsie Daisy!",
  "This Page Took a Vacation",
  "Uh-oh! Wrong Turn",
  "Page Not Found... But You Found Me!",
  "Are You Lost?",
  "Oops! Wrong Portal",
  "Out of Bounds",
  "Page Missing—Like Socks in the Dryer",
  "The Cake is a Lie",
  "Oops! Page Vanished",
  "Not Today!",
  "This Isn't the Webpage You're Looking For",
  "Page on Coffee Break",
  "Page Not Found, But Here's a Cat 🐱",
  "Page Went on an Adventure",
  "Page is Playing Hide and Seek",
  "Page Not Found, But You Found a Unicorn!",
  "Page is Out Chasing Butterflies",
  "Page is on a Coffee Run",
  "Page is Out to Lunch",
  "Page is on a Secret Mission",
  "Page is Napping",
  "Page is in Another Castle",
  "Page is in Stealth Mode",
  "Page is on Vacation",
  "Page is Out of Office",
  "Page is on a Snack Break",
  "Page is on a Road Trip",
  "Page is at the Beach",
  "Page is Exploring the Unknown",
  "Page is in the Upside Down",
  "Page is in a Parallel Universe",
  "Page is in a Galaxy Far, Far Away",
  "Page is in the Matrix",
  "Page is in Another Dimension",
  "Page is in the Bermuda Triangle",
  "Page is in the Twilight Zone",
  "Page is in a Black Hole",
  "Page is in a Wormhole",
  "Page is in a Time Loop",
  "Page is in a Parallel Reality",
  "Page is in a Secret Lair",
  "Page is in a Hidden Chamber",
  "Page is in a Secret Garden",
  "Page is in a Magical Forest",
  "Page is in a Haunted House",
  "Page is in a Pirate Ship",
  "Page is in a Spaceship",
  "Page is in a Submarine",
  "Page is in a Treehouse",
  "Page is in a Castle",
  "Page is in a Dungeon",
  "Page is in a Labyrinth",
  "Page is in a Maze",
  "Page is in a Secret Base",
  "Page is in a Hidden Cave",
  "Page is in a Cloud",
  "Page is in a Dream",
  "Page is in a Fantasy Land",
  "Page is in a Comic Book",
  "Page is in a Video Game",
  "Page is in a Board Game",
  "Page is in a Puzzle",
  "Page is in a Riddle",
  "Page is in a Joke",
  "Page is in a Meme",
  "Page is in a GIF",
  "Page is in a Emoji",
  "Page is in a Sticker",
  "Page is in a Doodle",
  "Page is in a Sketch",
  "Page is in a Painting",
  "Page is in a Sculpture",
  "Page is in a Song",
  "Page is in a Dance",
  "Page is in a Poem",
  "Page is in a Story",
  "Page is in a Legend",
  "Page is in a Myth",
  "Page is in a Fairy Tale",
  "Page is in a Fable",
  "Page is in a Tall Tale",
  "Page is in a Yarn",
  "Page is in a Saga",
  "Page is in a Chronicle",
  "Page is in a Epic",
  "Page is in a Quest",
  "Page is in a Journey",
  "Page is in a Adventure",
  "Page is in a Expedition",
  "Page is in a Voyage",
  "Page is in a Odyssey",
  "Page is in a Pilgrimage",
  "Page is in a Safari",
  "Page is in a Trek",
  "Page is in a Excursion",
  "Page is in a Tour",
  "Page is in a Trip",
  "Page is in a Getaway",
  "Page is in a Escape",
  "Page is in a Retreat",
  "Page is in a Hideaway",
  "Page is in a Sanctuary",
  "Page is in a Refuge",
  "Page is in a Haven",
  "Page is in a Oasis",
  "Page is in a Paradise",
  "Page is in a Utopia",
  "Page is in a Shangri-La",
  "Page is in a Wonderland",
  "Page is in a Neverland",
  "Page is in a Narnia",
  "Page is in a Oz",
  "Page is in a Middle-earth",
  "Page is in a Hogwarts",
  "Page is in a Westeros",
  "Page is in a Mordor",
  "Page is in a Asgard",
  "Page is in a Wakanda",
  "Page is in a Atlantis",
  "Page is in a El Dorado",
  "Page is in a Camelot",
  "Page is in a Avalon",
  "Page is in a Valhalla",
  "Looks like this page took a detour to the snack bar.",
  "This page is playing hide and seek. Spoiler: it's winning.",
  "'The page you seek is on a coffee break.",
  "Oops! This page is out chasing butterflies.",
  "The page you're looking for is off on an adventure.",
  "Sorry, this page is napping. Please try again later.",
  "This page is lost in the Bermuda Triangle.",
  "Page not found, but you found a secret!",
  "This page is on a top-secret mission.",
  "The page is out to lunch—literally.",
  "'Page is on a magical quest.",
  "This page is in another castle.",
  "Oops! The page is on a beach vacation.",
  "This page is exploring the upside down.",
  "Page not found, but here's a virtual high five!",
  "This page is in a parallel universe.",
  "'Page is in stealth mode.",
  "The page is on a road trip with no GPS.",
  "This page is in a galaxy far, far away.",
  "Oops! The page is in the Matrix.",
  "This page is in a time loop. Try again?",
  "Page not found, but you found a unicorn!",
  "This page is in a secret lair.",
  "'Page is in a hidden chamber.",
  "This page is in a magical forest.",
  "Oops! The page is in a haunted house.",
  "This page is sailing on a pirate ship.",
  "'Page is orbiting in a spaceship.",
  "This page is exploring the ocean in a submarine.",
  "Oops! The page is relaxing in a treehouse.",
  "This page is defending a castle.",
  "'Page is lost in a dungeon.",
  "This page is wandering a labyrinth.",
  "Oops! The page is stuck in a maze.",
  "This page is hiding in a secret base.",
  "'Page is spelunking in a cave.",
  "This page is floating on a cloud.",
  "Oops! The page is dreaming.",
  "This page is in a fantasy land.",
  "'Page is starring in a comic book.",
  "This page is a hidden level in a video game.",
  "Oops! The page is a missing puzzle piece.",
  "This page is a riddle wrapped in an enigma.",
  "'Page is telling a joke.",
  "This page is a meme in the making.",
  "Oops! The page is stuck in a GIF loop.",
  "This page is lost in emoji land.",
  "'Page is a sticker on your laptop.",
  "This page is a doodle in the margins.",
  "Oops! The page is a sketch on a napkin.",
  "This page is a painting in a secret gallery.",
  "'Page is a sculpture in a hidden museum.",
  "This page is singing a song.",
  "Oops! The page is dancing the night away.",
  "This page is writing a poem.",
  "'Page is telling a story.",
  "This page is a legend in its own mind.",
  "Oops! The page is a myth.",
  "This page is a fairy tale gone missing.",
  "'Page is a fable with no moral.",
  "This page is a tall tale.",
  "Oops! The page is spinning a yarn.",
  "This page is an epic saga.",
  "'Page is chronicling its adventures.",
  "This page is on a quest for meaning.",
  "Oops! The page is on a journey of self-discovery.",
  "This page is on an epic adventure.",
  "'Page is on an expedition.",
  "This page is on a voyage across the web.",
  "Oops! The page is on an odyssey.",
  "This page is on a pilgrimage.",
  "'Page is on safari.",
  "This page is trekking through the unknown.",
  "Oops! The page is on an excursion.",
  "This page is on a grand tour.",
  "'Page is on a trip to nowhere.",
  "This page is on a weekend getaway.",
  "Oops! The page is planning an escape.",
  "This page is on a retreat.",
  "'Page is hiding in a secret hideaway.",
  "This page is seeking sanctuary.",
  "Oops! The page is in a refuge.",
  "This page is relaxing in a haven.",
  "'Page is chilling in an oasis.",
  "This page is living in paradise.",
  "Oops! The page is searching for utopia.",
  "This page is meditating in Shangri-La.",
  "'Page is lost in Wonderland.",
  "This page is flying in Neverland.",
  "Oops! The page is exploring Narnia.",
  "This page is following the yellow brick road to Oz.",
  "'Page is hiking through Middle-earth.",
  "This page is learning magic at Hogwarts.",
  "Oops! The page is fighting dragons in Westeros.",
  "This page is climbing Mount Doom in Mordor.",
  "'Page is feasting in Asgard.",
  "This page is inventing in Wakanda.",
  "Oops! The page is diving in Atlantis.",
  "This page is searching for El Dorado.",
  "'Page is ruling Camelot.",
  "This page is resting in Avalon.",
  "Oops! The page is partying in Valhalla.",
  "This page is on a coffee run.",
  "'Page is on a snack break.",
  "This page is out of office.",
  "Oops! The page is on a secret mission.",
  "This page is in stealth mode.",
  "'Page is on vacation.",
  "This page is on a road trip.",
  "Oops! The page is at the beach.",
  "This page is exploring the unknown.",
  "'Page is in a parallel reality.",
  "This page is in a secret garden.",
  "Oops! The page is in a magical land.",
  "This page is in a hidden cave.",
  "'Page is in a dream world.",
  "This page is in a fantasy realm.",
  "Oops! The page is in a comic strip.",
  "This page is in a board game.",
  "'Page is in a puzzle box.",
  "This page is in a riddle book.",
  "Oops! The page is in a joke shop.",
  "This page is in a meme factory.",
  "'Page is in a GIF gallery.",
  "This page is in an emoji parade.",
  "Oops! The page is in a sticker album.",
  "This page is in a doodle pad.",
  "'Page is in a sketchbook.",
  "This page is in an art studio.",
  "Oops! The page is in a sculpture garden.",
  "This page is in a music hall.",
  "'Page is in a dance studio.",
  "This page is in a poetry slam.",
  "Oops! The page is in a storybook.",
  "This page is in a legendarium.",
  "'Page is in a mythos.",
  "This page is in a fairy circle.",
  "Oops! The page is in a fable forest.",
  "This page is in a tall tale tavern.",
  "'Page is in a yarn shop.",
  "This page is in a saga scroll.",
  "Oops! The page is in a chronicle chamber.",
  "This page is in an epic library.",
  "'Page is in a quest log.",
  "This page is in a journey journal.",
  "Oops! The page is in an adventure archive.",
  "This page is in an expedition diary.",
  "'Page is in a voyage vault.",
  "This page is in an odyssey opus.",
  "Oops! The page is in a pilgrimage path.",
  "This page is in a safari scrapbook.",
  "'Page is in a trek tracker.",
  "This page is in an excursion entry.",
  "Oops! The page is in a tour ticket.",
  "This page is in a trip itinerary.",
  "'Page is in a getaway guide.",
  "This page is in an escape plan.",
  "Oops! The page is in a retreat roster.",
  "This page is in a hideaway haven.",
  "'Page is in a sanctuary space.",
  "This page is in a refuge room.",
  "Oops! The page is in a haven hideout.",
  "This page is in an oasis oasis.",
  "'Page is in a paradise place.",
  "This page is in a utopia universe.",
  "Oops! The page is in a Shangri-La sanctuary.",
  "This page is in a Wonderland world.",
  "'Page is in a Neverland nook.",
  "This page is in a Narnia nook.",
  "Oops! The page is in an Oz oasis.",
  "This page is in a Middle-earth meadow.",
  "'Page is in a Hogwarts hall.",
  "This page is in a Westeros wood.",
  "Oops! The page is in a Mordor mountain.",
  "This page is in an Asgard arena.",
  "'Page is in a Wakanda workshop.",
  "This page is in an Atlantis abyss.",
  "Oops! The page is in an El Dorado enclave.",
  "This page is in a Camelot court.",
  "'Page is in an Avalon alcove.",
  "This page is in a Valhalla vault.",
];

export async function GET() {
  return NextResponse.json({ headerAmount: headers.length });
}
